
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('properties').del()
    .then(function () {
      // Inserts seed entries
      return knex('properties').insert([
        {address: '123 Main',
         unit: '1',
         city: 'Dallas',
         state: 'TX',
         zipcode: 75201,
         fname: 'Trevor',
         lname: 'Young',
         mortgage: 1000.00,
         property_tax: 130.50,
         property_insurance: 80.33,
         rent_amount: 1500.00,
         lease_start_date: 'Mon Nov 5 2017',
         lease_end_date: 'Mon Nov 5 2018',
         rent_paid: true,
         renewal_notice: false,
         repairs: false,
         repair_description:'none',
         repair_amount: 0,
         ytd_repairs: 200.00,
         ytd_mortgage: 8000.00,
         ytd_prop_tax: 1044.00,
         ytd_prop_ins: 642.64,
         ytd_rent: 12000.00,
         },
         {address: '4706 Twinleaf',
          unit: '',
          city: 'Gilbert',
          state: 'AZ',
          zipcode: 85296,
          fname: 'Austin',
          lname: 'Golhde',
          mortgage: 850.00,
          property_tax: 230.20,
          property_insurance: 80.00,
          rent_amount: 1400.00,
          lease_start_date: 'Mon Dec 5 2017',
          lease_end_date: 'Mon Dec 5 2018',
          rent_paid: true,
          renewal_notice: false,
          repairs: true,
          repair_description:'none',
          repair_amount: 0,
          ytd_repairs: 130.00,
          ytd_mortgage: 5100.00,
          ytd_prop_tax: 1561.20,
          ytd_prop_ins: 480.00,
          ytd_rent: 8400.00,
        },
        {address: '8955 Grenadier',
         unit: '',
         city: 'Dallas',
         state: 'TX',
         zipcode: 75238,
         fname: 'Ryan',
         lname: 'Golhde',
         mortgage: 1500.00,
         property_tax: 340.33,
         property_insurance: 92.00,
         rent_amount: 2250.00,
         lease_start_date: 'Mon Dec 5 2017',
         lease_end_date: 'Mon Dec 5 2018',
         rent_paid: true,
         renewal_notice: true,
         repairs: true,
         repair_description:'replace windows',
         repair_amount: 0,
         ytd_repairs: 130.00,
         ytd_mortgage: 13500.00,
         ytd_prop_tax: 3062.97,
         ytd_prop_ins: 828.00,
         ytd_rent: 20250,
       },
       {address: '515 E Grant',
        unit: '',
        city: 'Phoenix',
        state: 'AZ',
        zipcode: 88201,
        fname: 'Rahul',
        lname: 'Sherma',
        mortgage: 800.00,
        property_tax: 70.50,
        property_insurance: 60.33,
        rent_amount: 1200.00,
        lease_start_date: 'Mon Nov 5 2017',
        lease_end_date: 'Mon Nov 5 2018',
        rent_paid: true,
        renewal_notice: false,
        repairs: false,
        repair_description:'none',
        repair_amount: 0,
        ytd_repairs: 200.00,
        ytd_mortgage: 2400.00,
        ytd_prop_tax: 282.00,
        ytd_prop_ins: 241.32,
        ytd_rent: 4800.00,
        }
      ]);
    });
};
